version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: exchange_rates
            MYSQL_USER: exchange_rates
            MYSQL_PASSWORD: exchange_rates
    php:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./exchange_rates:/var/www/exchange_rates:cached
            - ./logs/exchange_rates:/var/www/exchange_rates/var/logs:cached
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    rabbitmq: # The RabbitMQ container.
        build:
            context: .
            dockerfile: Dockerfile-rabbitmq
        ports:
            - 15672:15672
