#index:
#    path: /
#    controller: App\Controller\DefaultController::index
xmlrpc:
  path: /xmlrpc
  controller: App\Controller\ExchangeRatesController::xmlRpcHandler

api_login_check:
  path: /api/login_check

fos_user_registration_register:
  path: /api/register
  controller: App\Controller\AuthController::register

